export const specialIndexFundSites = [
  {
    text: "vanguard",
    site: "vanguardinvestor.co.uk",
  },
  { text: "fidelity", site: "fidelity.co.uk" },
  { text: "ishares", site: "ishares.com" },
  { text: "blackrock", site: "blackrock.com" },
  { text: "spdr", site: "spdrs.com" },
  { text: "invesco", site: "invesco.com" },
  { text: "lyxor", site: "lyxoretf.co.uk" },
  { text: "wisdomtree", site: "wisdomtree.eu" },
  { text: "amundi", site: "amundietf.co.uk" },
  { text: "xtrackers", site: "xtrackers.com" },
  { text: "db x-trackers", site: "xtrackers.com" },
  { text: "db xtrackers", site: "xtrackers.com" },
] as const;

export const specialCryptoSites = [
  { text: "Bitcoin", site: "bitcoin.org", ticker: "BTC" },
  { text: "monero", site: "getmonero.org", ticker: "XMR" },
  { text: "Ethereum", site: "ethereum.org", ticker: "ETH" },
  { text: "Ripple", site: "ripple.com", ticker: "XRP" },
  { text: "Litecoin", site: "litecoin.org", ticker: "LTC" },
  { text: "Cardano", site: "cardano.org", ticker: "ADA" },
  { text: "Polkadot", site: "polkadot.network", ticker: "DOT" },
  { text: "Chainlink", site: "chain.link", ticker: "LINK" },
  { text: "Stellar", site: "stellar.org", ticker: "XLM" },
  { text: "Uniswap", site: "uniswap.org", ticker: "UNI" },
  { text: "Aave", site: "aave.com", ticker: "AAVE" },
  { text: "Compound", site: "compound.finance", ticker: "COMP" },
  { text: "Maker", site: "makerdao.com", ticker: "MKR" },
  { text: "Yearn", site: "yearn.finance", ticker: "YFI" },
  { text: "Sushi", site: "sushi.com", ticker: "SUSHI" },
  { text: "Synthetix", site: "synthetix.io", ticker: "SNX" },
  { text: "Curve", site: "curve.fi", ticker: "CRV" },
  { text: "Balancer", site: "balancer.finance", ticker: "BAL" },
  { text: "Ren", site: "renproject.io", ticker: "REN" },
  { text: "Kyber", site: "kyber.network", ticker: "KNC" },
  { text: "Loopring", site: "loopring.org", ticker: "LRC" },
  { text: "1inch", site: "1inch.io", ticker: "1INCH" },
  { text: "Zcash", site: "zcash.com", ticker: "ZEC" },
  { text: "Tezos", site: "tezos.com", ticker: "XTZ" },
  { text: "Algorand", site: "algorand.com", ticker: "ALGO" },
  { text: "Dai", site: "makerdao.com", ticker: "DAI" },
  { text: "Tether", site: "tether.to", ticker: "USDT" },
  { text: "USD Coin", site: "centre.io", ticker: "USDC" },
  { text: "Binance USD", site: "binance.com", ticker: "BUSD" },
  { text: "Paxos", site: "paxos.com", ticker: "PAX" },
  { text: "TrueUSD", site: "trusttoken.com", ticker: "TUSD" },
  { text: "Hedera", site: "hedera.com", ticker: "HBAR" },
  { text: "NEM", site: "nem.io", ticker: "XEM" },
  { text: "VeChain", site: "vechain.com", ticker: "VET" },
  { text: "ICON", site: "icon.foundation", ticker: "ICX" },
  { text: "Ontology", site: "ont.io", ticker: "ONT" },
  { text: "Qtum", site: "qtum.org", ticker: "QTUM" },
  { text: "Waves", site: "waves.tech", ticker: "WAVES" },
  { text: "Decred", site: "decred.org", ticker: "DCR" },
  { text: "Horizen", site: "horizen.global", ticker: "ZEN" },
  { text: "Nano", site: "nano.org", ticker: "NANO" },
  { text: "Nervos", site: "nervos.org", ticker: "CKB" },
  { text: "Zcoin", site: "zcoin.io", ticker: "XZC" },
  { text: "Aeternity", site: "aeternity.com", ticker: "AE" },
  { text: "Lisk", site: "lisk.com", ticker: "LSK" },
  { text: "Nebulas", site: "nebulas.io", ticker: "NAS" },
  { text: "Nxt", site: "nxt.org", ticker: "NXT" },
  { text: "Steem", site: "steem.com", ticker: "STEEM" },
  { text: "Stratis", site: "stratisplatform.com", ticker: "STRAT" },
  { text: "Syscoin", site: "syscoin.org", ticker: "SYS" },
  { text: "WAX", site: "wax.io", ticker: "WAXP" },
  { text: "Zencash", site: "horizen.global", ticker: "ZEN" },
  { text: "ZClassic", site: "zclassic.org", ticker: "ZCL" },
  { text: "Zilliqa", site: "zilliqa.com", ticker: "ZIL" },
] as const;
